server:
  port: 8000
debug: true
spring:
#  session:
#    store-type: redis
#    timeout: 1800
#    redis:
#      flush-mode: on-save
#      namespace: session:examples
#      cleanup-cron: 0/10 * * * * *
  redis:
    host: 127.0.0.1
    port: 6379
    password: null
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 5
    timeout: 30000